#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5
bspc monitor HDMI-A-0 1 2 3 4 5

bspc config focused_border_color "#fd971f"
bspc config normal_border_color "#f4bf75"
bspc config active_border_color "#f92672"
bspc config presel_feedback_color "#f4bf75"
# bspc config presel_feedback_opacity 100
bspc config border_width 5
bspc config borderless_monocle true

bspc config window_gap          20

bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr

bspc config split_ratio          0.52

# rules
bspc rule -a feh state=floating
bspc rule -a Tk state=floating

# start resources
xrdb -merge ~/.Xresources

~/.config/polybar/launch.sh &

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker
pkill battery-alert; ~/.config/bin/battery-alert &

# start picom
picom --config $HOME/.config/picom/picom.conf & 

bash $HOME/.config/bin/random_wallpaper